// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtz-hN3zcp3bzJDHtCKOZhUYh_kYcWNQs',
    appId: '1:626056020363:web:44b6aaa9c6c81c7f356f8e',
    messagingSenderId: '626056020363',
    projectId: 'TaskManagement',
    authDomain: 'TaskManagement.firebaseapp.com',
    storageBucket: 'TaskManagement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JaNGCZut6PuP97BNSjMNRAeAyESJ2ys',
    appId: '1:626056020363:android:a3ca9657cad27462356f8e',
    messagingSenderId: '626056020363',
    projectId: 'TaskManagement',
    storageBucket: 'TaskManagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuYay2LS6Rrn93q3LIUflGkwNoJjfH-bU',
    appId: '1:626056020363:ios:4ab659297dd6cc99356f8e',
    messagingSenderId: '626056020363',
    projectId: 'TaskManagement',
    storageBucket: 'TaskManagement.firebasestorage.app',
    iosBundleId: 'sunrack.com.taskmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuYay2LS6Rrn93q3LIUflGkwNoJjfH-bU',
    appId: '1:626056020363:ios:4ab659297dd6cc99356f8e',
    messagingSenderId: '626056020363',
    projectId: 'TaskManagement',
    storageBucket: 'TaskManagement.firebasestorage.app',
    iosBundleId: 'sunrack.com.taskmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtz-hN3zcp3bzJDHtCKOZhUYh_kYcWNQs',
    appId: '1:626056020363:web:6cd56f0d1c3d341d356f8e',
    messagingSenderId: '626056020363',
    projectId: 'TaskManagement',
    authDomain: 'TaskManagement.firebaseapp.com',
    storageBucket: 'TaskManagement.firebasestorage.app',
  );
}
